source 'https://rubygems.org'

gem 'sinatra'
gem 'pg'
gem 'pry'
gem 'sinatra-flash'
gem 'rspec'
gem 'capybara'
gem 'httparty'
gem 'rake'
gem 'sinatra-activerecord'
gem 'omniauth-github'
gem 'dotenv'
gem 'sinatra-reloader'
